export const designStyles = [
  {
    id: "modern-minimal",
    name: "现代简约",
    summary: "干净利落、收纳友好，适合大多数城市住宅。",
    keywords: "简洁线条,低饱和色,隐藏收纳,无主灯,温和对比",
    palette: "暖白、浅灰、木色、少量黑色线条",
    materials: "哑光柜门、木饰面、微水泥、细框玻璃",
    lighting: "无主灯、线性灯、局部洗墙光",
    negative: "避免复杂吊顶、过度金属、强烈花纹",
    roomTips: "客餐厅强调通透，卧室保持安静柔和。",
    sortOrder: 1,
  },
  {
    id: "italian-minimal",
    name: "意式极简",
    summary: "更高级克制，强调材质比例和低调质感。",
    keywords: "意式极简,高级灰,大板材,悬浮柜,低矮家具",
    palette: "灰咖、米白、炭黑、深木色",
    materials: "岩板、皮革、深色木饰面、金属窄边",
    lighting: "低位氛围光、磁吸轨道灯、局部重点光",
    negative: "避免亮色软装和繁复欧式线脚",
    roomTips: "适合客厅、主卧和开放式餐厨。",
    sortOrder: 2,
  },
  {
    id: "cream",
    name: "奶油风",
    summary: "柔和温暖，适合小户型和亲子家庭。",
    keywords: "奶油色,圆角,柔软织物,温馨,浅木色",
    palette: "奶油白、燕麦色、浅木色、浅咖",
    materials: "艺术漆、布艺、藤编、浅色木地板",
    lighting: "暖色灯带、柔光吊灯、落地灯",
    negative: "避免冷灰、黑色大面积对比、尖锐线条",
    roomTips: "儿童房和卧室可加入柔和色块。",
    sortOrder: 3,
  },
  {
    id: "natural-wood",
    name: "原木风",
    summary: "自然舒适，强调木质纹理和生活气息。",
    keywords: "原木,自然光,白墙,绿植,温润",
    palette: "白色、浅木、亚麻、少量绿色",
    materials: "橡木、藤编、棉麻、白色乳胶漆",
    lighting: "自然采光、暖白筒灯、纸灯",
    negative: "避免深色压抑、镜面材质和复杂造型",
    roomTips: "适合全屋统一风格，厨房注意耐污材质。",
    sortOrder: 4,
  },
  {
    id: "new-chinese",
    name: "新中式",
    summary: "东方秩序与现代生活结合，适合改善型住宅。",
    keywords: "东方留白,木格栅,山水意境,对称,雅致",
    palette: "米白、胡桃木、墨色、暖灰",
    materials: "木饰面、石材、宣纸纹理、金属细节",
    lighting: "暖色重点光、壁灯、隐藏灯带",
    negative: "避免仿古堆砌、红木过重、复杂雕花",
    roomTips: "客厅可做端景，卧室保持轻中式。",
    sortOrder: 5,
  },
  {
    id: "light-luxury",
    name: "轻奢",
    summary: "有精致感但不过度张扬，适合展示型空间。",
    keywords: "轻奢,精致,金属线条,石材纹理,高级软装",
    palette: "米白、香槟金、暖灰、咖色",
    materials: "岩板、金属线条、皮革、丝绒",
    lighting: "水晶感吊灯、灯带、重点射灯",
    negative: "避免土豪金、大面积镜面、过度装饰",
    roomTips: "客餐厅强化仪式感，卧室控制金属比例。",
    sortOrder: 6,
  },
  {
    id: "wabi-sabi",
    name: "侘寂风",
    summary: "安静、质朴、低饱和，强调肌理和留白。",
    keywords: "侘寂,微水泥,自然肌理,低饱和,留白",
    palette: "灰米、砂岩、泥土色、淡褐",
    materials: "微水泥、艺术漆、亚麻、粗陶",
    lighting: "柔和漫反射、壁龛灯、低亮度灯带",
    negative: "避免高亮金属、强色彩和复杂图案",
    roomTips: "适合卧室、书房和静谧客厅。",
    sortOrder: 7,
  },
  {
    id: "french",
    name: "法式",
    summary: "浪漫精致，以线条、比例和柔和色彩为主。",
    keywords: "法式线条,拱门,石膏线,复古,浪漫",
    palette: "象牙白、浅粉灰、奶咖、黄铜",
    materials: "石膏线、鱼骨拼地板、绒布、黄铜",
    lighting: "复古吊灯、壁灯、暖色氛围光",
    negative: "避免过多雕花、浓重宫廷感",
    roomTips: "小户型可用轻法式，减少厚重造型。",
    sortOrder: 8,
  },
  {
    id: "nordic",
    name: "北欧",
    summary: "清爽实用，色彩轻快，家具尺度友好。",
    keywords: "北欧,浅木,白墙,功能家具,清爽",
    palette: "白色、浅灰、浅木、低饱和蓝绿",
    materials: "木地板、棉麻、白色柜体、简洁瓷砖",
    lighting: "自然光、简洁吊灯、功能台灯",
    negative: "避免厚重深色和复杂吊顶",
    roomTips: "适合小户型和年轻家庭。",
    sortOrder: 9,
  },
  {
    id: "japanese",
    name: "日式",
    summary: "低矮、克制、温和，强调收纳和秩序。",
    keywords: "日式,榻榻米,移门,低矮家具,收纳",
    palette: "米白、浅木、草编色、暖灰",
    materials: "木格栅、障子门、榻榻米、棉麻",
    lighting: "纸灯、暖光、低位照明",
    negative: "避免高反光材料和强对比",
    roomTips: "适合书房、卧室和多功能房。",
    sortOrder: 10,
  },
  {
    id: "industrial",
    name: "工业风",
    summary: "粗粝、个性，适合开放式和年轻化空间。",
    keywords: "工业风,裸露管线,水泥,黑铁,复古皮革",
    palette: "水泥灰、黑色、锈红、深木",
    materials: "水泥漆、黑铁、砖墙、皮革",
    lighting: "轨道灯、复古灯泡、重点照明",
    negative: "避免过暗压抑和过多硬质材料",
    roomTips: "小户型需提高亮度和收纳比例。",
    sortOrder: 11,
  },
  {
    id: "american",
    name: "美式",
    summary: "舒适稳重，强调家具体量和生活感。",
    keywords: "美式,壁炉感,护墙板,舒适沙发,复古",
    palette: "米色、咖色、橄榄绿、深木",
    materials: "护墙板、实木家具、布艺、仿古砖",
    lighting: "吊灯、壁灯、台灯多层照明",
    negative: "避免家具过大导致动线拥挤",
    roomTips: "适合面积较大的客餐厅和主卧。",
    sortOrder: 12,
  },
  {
    id: "smart-tech",
    name: "智能科技",
    summary: "整洁、未来感，强调智能家居和灯光控制。",
    keywords: "智能家居,科技感,隐藏设备,灯光场景,简洁",
    palette: "白色、深灰、黑色、少量蓝色光感",
    materials: "玻璃、金属、哑光柜体、科技面板",
    lighting: "可调色温灯带、感应灯、场景灯光",
    negative: "避免过度蓝光和冰冷机房感",
    roomTips: "适合客厅、影音房和全屋智能展示。",
    sortOrder: 13,
  },
  {
    id: "family-warm",
    name: "亲子温馨",
    summary: "安全、柔和、耐用，适合有儿童的家庭。",
    keywords: "亲子,圆角,安全,耐污,活泼温暖",
    palette: "暖白、浅木、浅黄、低饱和彩色",
    materials: "环保板材、软包、耐污涂料、防滑地面",
    lighting: "柔光、夜灯、均匀照明",
    negative: "避免尖锐家具、玻璃过多和难清洁材质",
    roomTips: "儿童活动区重视安全边界和收纳。",
    sortOrder: 14,
  },
  {
    id: "senior-friendly",
    name: "适老舒适",
    summary: "安全、明亮、易维护，适合长辈居住。",
    keywords: "适老化,防滑,明亮,扶手,无障碍",
    palette: "暖白、浅木、米色、柔和灰",
    materials: "防滑地材、圆角家具、易清洁墙面",
    lighting: "高显色照明、夜间感应灯、无眩光",
    negative: "避免地面高差、强反光和过暗色调",
    roomTips: "卫生间、卧室和过道优先考虑安全。",
    sortOrder: 15,
  },
  {
    id: "boutique-hotel",
    name: "精品酒店风",
    summary: "有度假感和仪式感，强调灯光、材质和软装。",
    keywords: "精品酒店,度假感,套房,精致灯光,高级床品",
    palette: "暖灰、米咖、深木、黄铜点缀",
    materials: "石材、木饰面、织物硬包、金属细节",
    lighting: "多层灯光、床头吊灯、氛围灯带",
    negative: "避免商业感过重和维护困难材料",
    roomTips: "主卧、卫生间和客厅可增强酒店式体验。",
    sortOrder: 16,
  },
];
